package com.cg.healthcaresystem.centers.DTO;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Null;
import javax.validation.constraints.Pattern;

public class DiagnosticCenterDTO {
	@NotNull(message = "Center Name cannot be null")
	@Pattern(regexp = "^[A-Za-z]{3,30}$", message = "Center name should be atleast 3 character and maximum 30 characters.")
	private String centerName;
	@Null(message = "Center id not required. It is generated by the system.")
	private String centerId;
	@Pattern(regexp = "^[a-z A-Z 0-9,.]*$", message = "Special characters not allowed for address. ")
	@NotNull(message = "Center address cannot be null")
	private String centerAddress;
	@Pattern(regexp = "^[6-9]\\d{9}$", message = "Invalid phone number. ")
	@NotNull(message = "Contact number cannot be null")
	private String contactNumber;

	public DiagnosticCenterDTO(String centerName, String centerId, String centerAddress, String contactNumber) {
		super();
		this.centerName = centerName;
		this.centerId = centerId;
		this.centerAddress = centerAddress;
		this.contactNumber = contactNumber;
	}

	public DiagnosticCenterDTO() {

	}

	public String getCenterName() {
		return centerName;
	}

	public void setCenterName(String centerName) {
		this.centerName = centerName;
	}

	public String getCenterId() {
		return centerId;
	}

	public void setCenterId(String centerId) {
		this.centerId = centerId;
	}

	public String getCenterAddress() {
		return centerAddress;
	}

	public void setCenterAddress(String centerAddress) {
		this.centerAddress = centerAddress;
	}

	public String getContactNumber() {
		return contactNumber;
	}

	public void setContactNumber(String contactNumber) {
		this.contactNumber = contactNumber;
	}

	@Override
	public String toString() {
		return "DiagnosticCenterDTO [centerName=" + centerName + ", centerId=" + centerId + ", centerAddress="
				+ centerAddress + ", contactNumber=" + contactNumber + "]";
	}

}
